Develop amin
Integreat/integreat-cms pull request #608
Opened 2020-12-09 13:40 UTC by AminAlAit

### Short description

### Proposed changes

-
-
-

### Resolved issues

Fixes: #

2020-12-09 20:40 UTC, svenseeberg commented on src/cms/forms/imprints/imprint_translation_form.py
> +        page_translation = super().save(*args, **kwargs)
I think we should rename `page_translation` to `imprint_translation`. Makes sense, doesn't it?

2020-12-09 20:42 UTC, svenseeberg commented on src/cms/templates/imprints/imprint_form.html
> +            <button type="button" onclick="short_url_to_clipboard('s/p/{{ page_translation_form.instance.id }}');" class="cursor-pointer bg-blue-500 hover:bg-blue-600 text-white font-bold py-3 px-4 r
Not sure if we need a short URL at all for the imprint. But if we have it, we need to change the path. I'd say `i` for imprint? -> `s/i/IMPRINT_TRANSLATION_ID`.

2020-12-09 21:21 UTC, svenseeberg commented
The overall concept seems valid. Thank you for the contribution. Currently, lots of code is doubled. It would be cool to have some abstract classes and maybe even templates, so that the code can be shared with the page translations. @timoludwig do you agree?

2020-12-14 16:02 UTC, timoludwig requested changes
Thanks for your work. :+1: 

Please have a look at the [Page](https://integreat.github.io/integreat-cms/autogenerated/cms.models.pages.html#module-cms.models.pages.page) and [ImprintPage](https://integreat.github.io/integreat-cms/autogenerated/cms.models.pages.html#module-cms.models.pages.imprint_page) models and understand, that both have the same base class [AbstractBasePage](https://integreat.github.io/integreat-cms/autogenerated/cms.models.pages.html#module-cms.models.pages.abstract_base_page), but are different models with slightly different attributes etc.
There are multiple places where you just copied+pasted code for the wrong model. Copy+paste is a good start here, because the models are very similar and it doesn't make sense to re-invent the wheel, but since they're not the same, you have to understand the difference between these models and adapt the files you copied.
This includes e.g.:
- Please make sure to use the correct models (`ImprintPage` instead of `Page` etc)
- Use the correct permissions everywhere (`manage_imprint` instead of `edit_page` etc)
- Please remove any fields which are only relevant for the Page model
- Rename all variables

I tried to make suggestions, but probably didn't find all occurrences of wrong model usages etc, so please have a look again at the code you have copied + pasted and try to understand what it's doing.

Apart from that: Please log into [CircleCI](https://app.circleci.com/pipelines/github/Integreat/integreat-cms?branch=develop-amin), grant it access to your GitHub-account and restart the build to fix the "unauthorized" error

2020-12-14 16:07 UTC, timoludwig commented
> The overall concept seems valid. Thank you for the contribution. Currently, lots of code is doubled. It would be cool to have some abstract classes and maybe even templates, so that the code can be shared with the page translations. @timoludwig do you agree?

@svenseeberg I have noticed a lot of potential for improvement in our views/forms/templates code (not only page/imprint) and will probably make a major refactoring in the next couple of weeks. But I think it would ok to merge this PR and refactor afterwards.

2020-12-29 12:21 UTC, AminAlAit reviewed
.

2020-12-30 14:04 UTC, timoludwig approved these changes
@AminAlAit I rebased your branch onto the current develop branch and fixed all problems I noticed in the views. I think this is ready to merge now :tada:

2020-12-30 14:05 UTC, merged