Add content language switcher
Integreat/integreat-cms pull request #816
Opened 2021-05-09 14:56 UTC by timoludwig

### Short description

This adds a better content language switcher:

Collapsed             |  Expanded
:-------------------------:|:-------------------------:
![Screenshot_2021-05-09 Integreat Redaktionssystem](https://user-images.githubusercontent.com/16021269/117576085-c4758400-b0e4-11eb-8b20-835770e34f2f.png) |  ![Screenshot_2021-05-09 Integreat Redaktionssystem(1)](https://user-images.githubusercontent.com/16021269/117576068-b32c7780-b0e4-11eb-8e53-602dd8d2ce78.png)

### Proposed changes

- Add flackpack for svg flags
- Add constants for countries
- Add two possible countries per language
- Add language switcher

### Resolved issues

Fixes: #630

2021-05-10 09:52 UTC, svenseeberg commented
I noticed one GUI glitch with the drop down:
![myimage](https://user-images.githubusercontent.com/15197000/117641163-21754680-b186-11eb-97f0-5cf1abf486ca.gif)

2021-05-10 09:57 UTC, svenseeberg commented
It would be easiest to merge #818 into this branch before merging into the develop branch.

2021-05-10 15:55 UTC, ulliholtgrave commented
I have the same issue, but I think it's not that annoying. If we really have to, we might add a extra div around the chevron that keeps the size.

2021-05-10 16:25 UTC, svenseeberg requested changes
I have not found any major issues. It works with a minor GUI glitch in my Firefox. I think fixing the GUI glitch could be part of a bug fix later on. There is one typo in the inactive constants.

2021-05-10 16:25 UTC, svenseeberg commented on src/cms/constants/countries.py
> +INCATIVE_CHOICES = (
`INACTIVE_CHOICES` ?

2021-05-11 06:56 UTC, svenseeberg approved these changes
I wrote my last comment before I read that you already fixed it. So yes, good to merge!

2021-05-11 07:42 UTC, merged