Add tablesort functionality to all tables
Integreat/integreat-cms pull request #841
Opened 2021-05-17 19:20 UTC by emmakemb

### Short description
Short description

At the moment, only the event list can be sorted.
Proposed Solution

### Proposed changes

Add the same tablesort functionality to all our tables:

    Regions
    Languages
    Admin Users
    Region Users
    Organizations
    Offer Templates
    Admin Feedback
    Region Feedback
    Push Notifications

### Resolved issues

Fixes: #624

2021-05-31 00:16 UTC, timoludwig requested changes
Thanks for your PR! :+1:

I think there was a misunderstanding: `data-sort-method="none"` should only be added when the column does not contain data which can be sorted, such as:
- Checkboxes
- Country Flags
- Options/Actions

In all other cases, we want to keep the option of sorting by that column (not just the first column).

2021-05-31 00:16 UTC, timoludwig commented on src/cms/templates/offer_templates/offer_template_list.html
> +                <th class="text-sm text-left uppercase py-3 p2-4 pr-4 minno-sort" data-sort-method="none">{% trans 'Options' %}</th>
```suggestion
	            <th class="text-sm text-left uppercase py-3 px-2">{% trans 'Slug' %}</th>
	            <th class="text-sm text-left uppercase py-3 px-2">{% trans 'URL' %}</th>
	            <th class="text-sm text-left uppercase py-3 px-2">{% trans 'Last updated' %}</th>
	            <th class="text-sm text-left uppercase py-3 px-2">{% trans 'Created' %}</th>
                <th class="text-sm text-left uppercase py-3 p2-4 pr-4 min no-sort" data-sort-method="none">{% trans 'Options' %}</th>
```

2021-05-31 00:16 UTC, timoludwig commented on src/cms/templates/organizations/organization_list.html
> +                <th class="text-sm text-left uppercase py-3 p2-4 pr-4 min no-sort " data-sort-method="none">{% trans 'Options' %}</th>
```suggestion
                <th class="text-sm text-left uppercase py-3 pl-4 pr-2" >{% trans 'Name' %}</th>
                <th class="text-sm text-left uppercase py-3 px-2">{% trans 'Slug' %}</th>
                <th class="text-sm text-left uppercase py-3 px-2">{% trans 'Thumbnail' %}</th>
                <th class="text-sm text-left uppercase py-3 p2-4 pr-4 min no-sort" data-sort-method="none">{% trans 'Options' %}</th>
```

2021-05-31 00:16 UTC, timoludwig commented on src/cms/templates/push_notifications/push_notification_list.html
> +                <th class="text-sm text-left uppercase py-3 px-2 no-sort" data-sort-method="none">
```suggestion
                <th class="text-sm text-left uppercase py-3 px-2">
```

2021-05-31 00:16 UTC, timoludwig commented on src/cms/templates/push_notifications/push_notification_list.html
> +                <th class="text-sm text-left uppercase py-3 px-2 min no-sort" data-sort-method="none">
```suggestion
                <th class="text-sm text-left uppercase py-3 px-2 min">
```

2021-05-31 00:16 UTC, timoludwig commented on src/cms/templates/regions/region_list.html
> +                <th class="text-sm text-left uppercase py-3 px-2 min no-sort" data-sort-method="none">{% trans 'Status' %}</th>
```suggestion
                <th class="text-sm text-left uppercase py-3 px-2">{% trans 'Created' %}</th>
                <th class="text-sm text-left uppercase py-3 px-2">{% trans 'Last updated' %}</th>
                <th class="text-sm text-left uppercase py-3 px-2 min">{% trans 'Status' %}</th>
```

2021-05-31 00:16 UTC, timoludwig commented on src/cms/templates/users/admin/list.html
> +                <th class="text-sm text-left uppercase py-3 pl-2 pr-4 min no-sort" data-sort-method="none">{% trans 'Administrator' %}</th>
```suggestion
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'First Name' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'Last Name' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'E-mail-address' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'Organization' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'Last Login' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'Active' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2 min">{% trans 'Staff' %}</th>
                <th class="text-sm text-left uppercase py-3 pl-2 pr-4 min">{% trans 'Administrator' %}</th>
```

2021-05-31 00:16 UTC, timoludwig commented on src/cms/templates/users/region/list.html
> +                <th class="text-sm text-left uppercase py-3 pr-4 min no-sort" data-sort-method="none">{% trans 'Active' %}</th>
```suggestion
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'First Name' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'Last Name' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'E-mail-address' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'Organization' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-2">{% trans 'Last Login' %}</th>
                <th class="text-sm text-left uppercase py-3 pr-4 min">{% trans 'Active' %}</th>
```

2021-06-06 15:46 UTC, mael-fosso commented on src/cms/templates/feedback/admin_feedback_list.html
> +            <th class="text-sm text-right uppercase py-3 pr-2 no-sort" data-sort-method="none">{% trans 'Date' %}</th>
for me it should not have made sense to perform a sort according to these columns

2021-06-06 15:58 UTC, mael-fosso commented on src/cms/templates/feedback/admin_feedback_list.html
>          <tr class="border-b border-solid border-gray-200">
it escaped me

2021-06-06 17:20 UTC, mael-fosso commented on src/cms/templates/feedback/admin_feedback_list.html
>              <th class="text-sm text-left uppercase py-3 pr-2" style="padding-left: 10px;" title="{% trans 'Select all' %}"><input type="checkbox" id="bulk-select-all"></th>
ok

2021-06-21 22:12 UTC, timoludwig commented on src/cms/templates/feedback/admin_feedback_list.html
>              <th class="text-sm text-left uppercase py-3 pr-2" style="padding-left: 10px;" title="{% trans 'Select all' %}"><input type="checkbox" id="bulk-select-all"></th>
This is not resolved yet, please add `data-sort-method="none"` and the class `no-sort` for the checkbox column of the admin feedback list.

2021-06-21 22:13 UTC, timoludwig commented on src/cms/templates/feedback/region_feedback_list.html
>              <th class="text-sm text-left uppercase py-3 pr-2" style="padding-left: 10px;" title="{% trans 'Select all' %}"><input type="checkbox" id="bulk-select-all"></th>
This is not resolved yet either.

2021-06-21 22:17 UTC, timoludwig commented on src/cms/templates/push_notifications/push_notification_list.html
> +                <th class="text-sm text-left uppercase py-3 px-2 no-sort" data-sort-method="none">
This is not solved yet.

2021-06-21 22:18 UTC, timoludwig commented on src/cms/templates/push_notifications/push_notification_list.html
> +                <th class="text-sm text-left uppercase py-3 px-2 min no-sort" data-sort-method="none">
This is not resolved yet.

2021-06-21 22:21 UTC, timoludwig requested changes
Thanks for your changes! :+1:
Sorry that it took me so long to review your PR!
In general it looks good, there are just a few comments from last time which are not resolved yet. I commented each entry which is still missing.
Thanks again!

2021-07-07 08:38 UTC, ulliholtgrave commented
As we are no longer needing this changes I'll close this PR for now, but thank you @mael-fosso & @emmakemb  very much for your effort :+1: :)

2021-07-07 08:38 UTC, closed without merging