Add SQL caching
Integreat/integreat-cms pull request #940
Opened 2021-09-22 16:01 UTC by timoludwig

### Short description

This PR adds the plugin [django-cachalot](https://django-cachalot.readthedocs.io/en/latest/) which uses the Memcached client [pymemcache](https://pymemcache.readthedocs.io/en/latest/getting_started.html) to connect to a Memcached server running on localhost (has to be installed separately).

### Proposed changes

- Update all pip dependencies
- Add [ipython](https://ipython.readthedocs.io/en/stable/) for better debug shell
- Add [django-debug-toolbar](https://django-debug-toolbar.readthedocs.io/en/latest/)
- Add [django-cachalot](https://django-cachalot.readthedocs.io/en/latest/) and [Memcached client](https://pymemcache.readthedocs.io/en/latest/getting_started.html)

If you want to try this out, you have to install a local Memcached server on your machine. E.g. on Ubuntu, do:
```
sudo apt install memcached
sudo systemctl start memcached
```

### Resolved issues

Fixes (partially): #886

2021-09-27 11:01 UTC, svenseeberg requested changes
Looking forward to seeing this in action :D I found one problem and one addition I'd like to have.

2021-09-27 16:33 UTC, timoludwig commented on src/backend/urls.py
> +import debug_toolbar
Ah, good point! I found out, that the url config can also be passed as module string, which is then imported by the url utility...

2021-09-27 16:34 UTC, timoludwig commented on src/backend/settings.py
> +        "LOCATION": "redis://127.0.0.1:6379/1",
Good idea, I added the option to pass the path to a unix socket via the environment variable `DJANGO_REDIS_UNIX_SOCKET`.

2021-09-28 11:29 UTC, svenseeberg approved these changes

2021-09-28 11:42 UTC, merged